/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/login/access-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Access Token */
        post: operations["login-login_access_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/test-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Token */
        post: operations["login-test_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/password-recovery/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recover Password */
        post: operations["login-recover_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reset-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["login-reset_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/password-recovery-html-content/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recover Password Html Content */
        post: operations["login-recover_password_html_content"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Users */
        get: operations["users-read_users"];
        put?: never;
        /** Create User */
        post: operations["users-create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read User Me */
        get: operations["users-read_user_me"];
        put?: never;
        post?: never;
        /** Delete User Me */
        delete: operations["users-delete_user_me"];
        options?: never;
        head?: never;
        /** Update User Me */
        patch: operations["users-update_user_me"];
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Password Me */
        patch: operations["users-update_password_me"];
        trace?: never;
    };
    "/api/v1/users/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register User */
        post: operations["users-register_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read User By Id */
        get: operations["users-read_user_by_id"];
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["users-delete_user"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["users-update_user"];
        trace?: never;
    };
    "/api/v1/utils/test-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Email */
        post: operations["utils-test_email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/utils/health-check/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["utils-health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/navigation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Navigation Config */
        get: operations["config-get_navigation_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/user-menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Menu Config */
        get: operations["config-get_user_menu_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Apps Config */
        get: operations["config-get_apps_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Routes */
        get: operations["config-get_routes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pages Config */
        get: operations["config-get_pages_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/pages/{app_key}/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page Config */
        get: operations["config-get_page_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/pages/{app_key}/{path}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page Content */
        get: operations["config-get_page_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Unified search across records, actions, navigation items, custom pages, and help.
         */
        get: operations["config-search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{app_key}/{path}/download_pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Pdf */
        get: operations["pages-download_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{app_key}/{path}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Render Page */
        get: operations["pages-render_page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{app_key}/{path}/action/{action_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Action */
        post: operations["pages-execute_action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/launchpad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Launchpad Config */
        get: operations["config-get_launchpad_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Modules */
        get: operations["config-list_modules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/modules/{entity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Module */
        get: operations["config-get_module"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/modules/{entity}/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Module Recent */
        get: operations["config-get_module_recent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/{module}/{operation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Data Endpoint
         * @description Unified data endpoint for all CRUD, queries, and actions.
         *
         *     operation: list | read | create | update | delete | <named_operation>
         */
        post: operations["data-data_endpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/functions/{module}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Functions
         * @description Returns available named operations for a module (for debugging/admin).
         */
        get: operations["data-list_functions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Endpoint
         * @description Execute multiple operations in a transaction.
         *     All operations succeed or all fail together.
         */
        post: operations["data-batch_endpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/select/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Select Options */
        post: operations["select-get_select_options"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{app_key}/{entity}/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Render Document
         * @description Render a document template with record data.
         *     Returns processed HTML ready for PDF generation.
         */
        get: operations["documents-render_document"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/private/server-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server Info */
        get: operations["private-server_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionApi */
        ActionApi: {
            /** Endpoint */
            endpoint: string;
            /**
             * Method
             * @enum {string}
             */
            method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
            /** Headers */
            headers?: {
                [key: string]: string;
            } | null;
            /** Body */
            body?: {
                [key: string]: unknown;
            } | null;
            /** Params */
            params?: {
                [key: string]: string;
            } | null;
            /** Successmessage */
            successMessage?: string | null;
            /** Errormessage */
            errorMessage?: string | null;
            /** Onsuccess */
            onSuccess?: ("reload" | "navigate" | "navigateList" | "close" | "none") | null;
            /** Navigateto */
            navigateTo?: string | null;
        };
        /** ActionConfig */
        ActionConfig: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Icon */
            icon: string;
            /**
             * Type
             * @enum {string}
             */
            type: "builtin" | "custom";
            /** Builtintype */
            builtinType?: ("edit" | "delete" | "duplicate" | "download" | "print" | "navigate") | null;
            /** Location */
            location?: ("header" | "row" | "bulk" | "overflow")[];
            /** Variant */
            variant?: ("filled" | "light" | "outline" | "subtle" | "default") | null;
            /** Color */
            color?: string | null;
            /**
             * Order
             * @default 0
             */
            order: number;
            visible?: components["schemas"]["ActionVisibility"] | null;
            confirm?: components["schemas"]["ActionConfirm"] | null;
            /** Templates */
            templates?: components["schemas"]["ActionTemplate"][];
            api?: components["schemas"]["ActionApi"] | null;
            /** Href */
            href?: string | null;
            /**
             * Overflow
             * @default false
             */
            overflow: boolean;
        };
        /** ActionConfirm */
        ActionConfirm: {
            /** Title */
            title: string;
            /** Message */
            message: string;
            /** Confirmlabel */
            confirmLabel?: string | null;
            /** Cancellabel */
            cancelLabel?: string | null;
            /** Confirmcolor */
            confirmColor?: string | null;
            /** Requireinput */
            requireInput?: string | null;
        };
        /** ActionTemplate */
        ActionTemplate: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
            /** Icon */
            icon?: string | null;
            /** Format */
            format?: string | null;
            /** Endpoint */
            endpoint?: string | null;
        };
        /** ActionVisibility */
        ActionVisibility: {
            /** Field */
            field?: string | null;
            /** Equals */
            equals?: string | null;
            /** Context */
            context?: ("view" | "edit" | "create" | "list")[] | null;
            /** Permission */
            permission?: string | null;
        };
        /** ApiResponse[CustomPageConfig] */
        ApiResponse_CustomPageConfig_: {
            data: components["schemas"]["CustomPageConfig"];
            meta?: components["schemas"]["EnvelopeMeta"] | null;
        };
        /** ApiResponse[NavigationConfig] */
        ApiResponse_NavigationConfig_: {
            data: components["schemas"]["NavigationConfig"];
            meta?: components["schemas"]["EnvelopeMeta"] | null;
        };
        /** ApiResponse[dict[str, AppConfig]] */
        ApiResponse_dict_str__AppConfig__: {
            /** Data */
            data: {
                [key: string]: components["schemas"]["AppConfig"];
            };
            meta?: components["schemas"]["EnvelopeMeta"] | null;
        };
        /** ApiResponse[dict[str, CustomPageConfig]] */
        ApiResponse_dict_str__CustomPageConfig__: {
            /** Data */
            data: {
                [key: string]: components["schemas"]["CustomPageConfig"];
            };
            meta?: components["schemas"]["EnvelopeMeta"] | null;
        };
        /** ApiResponse[list[RouteDef]] */
        ApiResponse_list_RouteDef__: {
            /** Data */
            data: components["schemas"]["RouteDef"][];
            meta?: components["schemas"]["EnvelopeMeta"] | null;
        };
        /** ApiResponse[list[UserMenuItem]] */
        ApiResponse_list_UserMenuItem__: {
            /** Data */
            data: components["schemas"]["UserMenuItem"][];
            meta?: components["schemas"]["EnvelopeMeta"] | null;
        };
        /** AppConfig */
        AppConfig: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Icon */
            icon: string;
            /** Color */
            color: string;
            /**
             * Has Dashboard
             * @default true
             */
            has_dashboard: boolean;
            /** Entities */
            entities?: string[];
            /** Nav Items */
            nav_items?: components["schemas"]["AppNavItem"][];
        };
        /** AppNavItem */
        AppNavItem: {
            /** Label */
            label: string;
            /** Icon */
            icon: string;
            /** Entity */
            entity: string;
            /**
             * Action
             * @enum {string}
             */
            action: "list" | "create" | "edit" | "view" | "reports";
            /** Description */
            description?: string | null;
        };
        /** AppStatResolved */
        AppStatResolved: {
            /** Label */
            label: string;
            /** Value */
            value: string | null;
            /** Trend */
            trend: string | null;
        };
        /** Body_login-login_access_token */
        "Body_login-login_access_token": {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** CustomPageConfig */
        CustomPageConfig: {
            /** App Key */
            app_key: string;
            /** Path */
            path: string;
            /** Title */
            title: string;
            /** Actions */
            actions?: components["schemas"]["ActionConfig"][];
            html_content: components["schemas"]["HtmlContentConfig"];
        };
        /** DataRequest */
        DataRequest: {
            /** Operation */
            operation?: string | null;
            /** Params */
            params?: {
                [key: string]: unknown;
            } | null;
            /** Body */
            body?: {
                [key: string]: unknown;
            } | null;
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
        };
        /** EnvelopeMeta */
        EnvelopeMeta: {
            /** Total */
            total?: number | null;
            /** Page */
            page?: number | null;
            /** Page Size */
            page_size?: number | null;
            /** Sort */
            sort?: string | null;
            /** Filter */
            filter?: {
                [key: string]: unknown;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HomeItem */
        HomeItem: {
            /**
             * Label
             * @default Home
             */
            label: string;
            /**
             * Icon
             * @default home
             */
            icon: string;
            /**
             * Href
             * @default /
             */
            href: string;
            /**
             * Description
             * @default Hera Cloud Launchpad
             */
            description: string;
        };
        /** HtmlContentConfig */
        HtmlContentConfig: {
            /** Endpoint */
            endpoint: string;
            /**
             * Method
             * @enum {string}
             */
            method: "GET" | "POST";
            /** Headers */
            headers?: {
                [key: string]: string;
            } | null;
            /** Params */
            params?: {
                [key: string]: string;
            } | null;
            /** Body */
            body?: {
                [key: string]: unknown;
            } | null;
            /** Data Params */
            data_params?: string[];
        };
        /** LaunchpadAppResolved */
        LaunchpadAppResolved: {
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            /** Href */
            href: string;
            /** Color */
            color: string;
            /** Stats */
            stats?: components["schemas"]["AppStatResolved"][];
        };
        /** LaunchpadConfigResolved */
        LaunchpadConfigResolved: {
            /** Pages */
            pages?: components["schemas"]["QuickAccessPage"][];
            /** Apps */
            apps?: components["schemas"]["LaunchpadAppResolved"][];
            /** Tiles */
            tiles?: components["schemas"]["LaunchpadTileResolved"][];
        };
        /** LaunchpadTileResolved */
        LaunchpadTileResolved: {
            /** Title */
            title: string;
            /** Value */
            value: string | null;
            /** Subtitle */
            subtitle: string | null;
            /** Icon */
            icon: string;
            /** Color */
            color: string;
            /** Trend */
            trend: string | null;
            /** Trendvalue */
            trendValue: string | null;
        };
        /** Message */
        Message: {
            /** Message */
            message: string;
        };
        /** NavigationConfig */
        NavigationConfig: {
            home?: components["schemas"]["HomeItem"];
            /** Groups */
            groups?: components["schemas"]["NavigationGroup"][];
        };
        /** NavigationGroup */
        NavigationGroup: {
            /** Group Label */
            group_label: string;
            /** Group Slug */
            group_slug: string;
            /**
             * Has Dashboard
             * @default true
             */
            has_dashboard: boolean;
            /** Items */
            items?: components["schemas"]["NavigationItem"][];
        };
        /** NavigationItem */
        NavigationItem: {
            /** Label */
            label: string;
            /** Icon */
            icon: string;
            /** Entity */
            entity: string;
            /**
             * Action
             * @enum {string}
             */
            action: "list" | "create" | "edit" | "view" | "reports";
            /** Description */
            description?: string | null;
            /** Color */
            color?: string | null;
        };
        /** NewPassword */
        NewPassword: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /** QuickAccessPage */
        QuickAccessPage: {
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            /** Href */
            href: string;
            /** Color */
            color: string;
        };
        /** RouteDef */
        RouteDef: {
            /** Key */
            key: string;
            /** Pattern */
            pattern: string;
            /** Component */
            component: string;
            /**
             * Authrequired
             * @default true
             */
            authRequired: boolean;
            /** Title */
            title?: string | null;
            /** Appkey */
            appKey?: string | null;
            /** Entitykey */
            entityKey?: string | null;
            /** Custompagekey */
            customPageKey?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Data */
            data: components["schemas"]["SearchResult"][];
            meta?: components["schemas"]["EnvelopeMeta"] | null;
        };
        /** SearchResult */
        SearchResult: {
            /**
             * Type
             * @enum {string}
             */
            type: "record" | "action" | "nav" | "page" | "help";
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
            /** Path */
            path?: string | null;
            /** Icon */
            icon?: string | null;
            /** Module */
            module?: string | null;
            /** Score */
            score?: number | null;
        };
        /** SelectOptionsRequest */
        SelectOptionsRequest: {
            /** Entity */
            entity: string;
            /** Fieldkey */
            fieldKey: string;
            /** Values */
            values?: {
                [key: string]: string | number | boolean | null;
            };
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UpdatePassword */
        UpdatePassword: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /** Full Name */
            full_name?: string | null;
            /** Password */
            password: string;
        };
        /** UserMenuItem */
        UserMenuItem: {
            /** Label */
            label: string;
            /** Icon */
            icon: string;
            /** Href */
            href: string;
            /** Action */
            action?: string | null;
            /** Color */
            color?: string | null;
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /** Full Name */
            full_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Created At */
            created_at?: string | null;
        };
        /** UserRegister */
        UserRegister: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name?: string | null;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Email */
            email?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /** Full Name */
            full_name?: string | null;
            /** Password */
            password?: string | null;
        };
        /** UserUpdateMe */
        UserUpdateMe: {
            /** Full Name */
            full_name?: string | null;
            /** Email */
            email?: string | null;
        };
        /** UsersPublic */
        UsersPublic: {
            /** Data */
            data: components["schemas"]["UserPublic"][];
            /** Count */
            count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaActionApi = components['schemas']['ActionApi'];
export type SchemaActionConfig = components['schemas']['ActionConfig'];
export type SchemaActionConfirm = components['schemas']['ActionConfirm'];
export type SchemaActionTemplate = components['schemas']['ActionTemplate'];
export type SchemaActionVisibility = components['schemas']['ActionVisibility'];
export type SchemaApiResponseCustomPageConfig = components['schemas']['ApiResponse_CustomPageConfig_'];
export type SchemaApiResponseNavigationConfig = components['schemas']['ApiResponse_NavigationConfig_'];
export type SchemaApiResponseDictStrAppConfig = components['schemas']['ApiResponse_dict_str__AppConfig__'];
export type SchemaApiResponseDictStrCustomPageConfig = components['schemas']['ApiResponse_dict_str__CustomPageConfig__'];
export type SchemaApiResponseListRouteDef = components['schemas']['ApiResponse_list_RouteDef__'];
export type SchemaApiResponseListUserMenuItem = components['schemas']['ApiResponse_list_UserMenuItem__'];
export type SchemaAppConfig = components['schemas']['AppConfig'];
export type SchemaAppNavItem = components['schemas']['AppNavItem'];
export type SchemaAppStatResolved = components['schemas']['AppStatResolved'];
export type SchemaBodyLoginLoginAccessToken = components['schemas']['Body_login-login_access_token'];
export type SchemaCustomPageConfig = components['schemas']['CustomPageConfig'];
export type SchemaDataRequest = components['schemas']['DataRequest'];
export type SchemaEnvelopeMeta = components['schemas']['EnvelopeMeta'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaHomeItem = components['schemas']['HomeItem'];
export type SchemaHtmlContentConfig = components['schemas']['HtmlContentConfig'];
export type SchemaLaunchpadAppResolved = components['schemas']['LaunchpadAppResolved'];
export type SchemaLaunchpadConfigResolved = components['schemas']['LaunchpadConfigResolved'];
export type SchemaLaunchpadTileResolved = components['schemas']['LaunchpadTileResolved'];
export type SchemaMessage = components['schemas']['Message'];
export type SchemaNavigationConfig = components['schemas']['NavigationConfig'];
export type SchemaNavigationGroup = components['schemas']['NavigationGroup'];
export type SchemaNavigationItem = components['schemas']['NavigationItem'];
export type SchemaNewPassword = components['schemas']['NewPassword'];
export type SchemaQuickAccessPage = components['schemas']['QuickAccessPage'];
export type SchemaRouteDef = components['schemas']['RouteDef'];
export type SchemaSearchResponse = components['schemas']['SearchResponse'];
export type SchemaSearchResult = components['schemas']['SearchResult'];
export type SchemaSelectOptionsRequest = components['schemas']['SelectOptionsRequest'];
export type SchemaToken = components['schemas']['Token'];
export type SchemaUpdatePassword = components['schemas']['UpdatePassword'];
export type SchemaUserCreate = components['schemas']['UserCreate'];
export type SchemaUserMenuItem = components['schemas']['UserMenuItem'];
export type SchemaUserPublic = components['schemas']['UserPublic'];
export type SchemaUserRegister = components['schemas']['UserRegister'];
export type SchemaUserUpdate = components['schemas']['UserUpdate'];
export type SchemaUserUpdateMe = components['schemas']['UserUpdateMe'];
export type SchemaUsersPublic = components['schemas']['UsersPublic'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    "login-login_access_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login-login_access_token"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "login-test_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    "login-recover_password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "login-reset_password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPassword"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "login-recover_password_html_content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-read_users": {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsersPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-create_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-read_user_me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    "users-delete_user_me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    "users-update_user_me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateMe"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-update_password_me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePassword"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-register_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-read_user_by_id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-delete_user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-update_user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "utils-test_email": {
        parameters: {
            query: {
                email_to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "utils-health_check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    "config-get_navigation_config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NavigationConfig_"];
                };
            };
        };
    };
    "config-get_user_menu_config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_UserMenuItem__"];
                };
            };
        };
    };
    "config-get_apps_config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_str__AppConfig__"];
                };
            };
        };
    };
    "config-get_routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_RouteDef__"];
                };
            };
        };
    };
    "config-get_pages_config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_str__CustomPageConfig__"];
                };
            };
        };
    };
    "config-get_page_config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_key: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CustomPageConfig_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "config-get_page_content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_key: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "config-search": {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "pages-download_pdf": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_key: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "pages-render_page": {
        parameters: {
            query?: {
                entity?: string | null;
                filters?: string | null;
            };
            header?: never;
            path: {
                app_key: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "pages-execute_action": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_key: string;
                path: string;
                action_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "config-get_launchpad_config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaunchpadConfigResolved"];
                };
            };
        };
    };
    "config-list_modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    "config-get_module": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "config-get_module_recent": {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                entity: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "data-data_endpoint": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: string;
                operation: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "data-list_functions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "data-batch_endpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataRequest"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "select-get_select_options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectOptionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "documents-render_document": {
        parameters: {
            query?: {
                template_key?: string;
            };
            header?: never;
            path: {
                app_key: string;
                entity: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "private-server_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
